# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


#
def open_specs_pods
    pod 'Masonry', '~> 1.1.0'
 
end

def mine_specs_pods
    pod 'AFNetworking', '~> 4.0.0'
 
end


target 'teset1' do
  use_frameworks!

    open_specs_pods
    mine_specs_pods

end
